Arrays

In [1]:
import numpy as np

In [6]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a.shape

(2, 3)

In [9]:
a[1,2]

6

In [10]:
a[0]

array([1, 2, 3])

In [12]:
import random

In [15]:
prob = random.random()
print(prob)

0.18368019428708815


In [17]:
number = random.randint(1,6)
print(number)

3


In [18]:
import numpy as np

In [20]:
np.random.randint(1,10,(5,5))

array([[7, 6, 8, 5, 1],
       [1, 1, 3, 2, 9],
       [2, 7, 9, 2, 6],
       [7, 3, 5, 9, 7],
       [2, 4, 1, 2, 6]])